name: tozauz_agent
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # to use svg icons
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.6
  # state mangment
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  get_it: ^8.0.3
  # use json decode
  #  freezed: ^2.4.3
  #  json_serializable: ^6.7.0
  #  json_annotation: ^4.9.0
  #  dartz: ^0.10.1
  #  freezed_annotation: ^2.4.1
  # for api
  dio: ^5.5.0+1
  # Flutter plugin for local db for small data
  shared_preferences: ^2.0.6
  # use for shimmer loading
  shimmer: ^3.0.0
  # The package provides TextInputFormatter for TextField and TextFormField
  # which format the input by a given mask.
  mask_text_input_formatter: ^2.5.0
  # Connect your translations in Flutter
  intl: ^0.19.0
  intl_utils: ^2.8.5
  # for animation
  animate_do: ^4.2.0
  #  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.0
  # for animation button
  scale_button: ^2.1.2
  # for map and location
  #  yandex_mapkit: ^4.1.0
  #  geolocator: ^13.0.1
  # for permission
  permission_handler: ^11.4.0
  #
  expandable_bottom_sheet: ^1.1.1+1
  # Circular and Linear percent indicators
  #  percent_indicator: ^4.2.3
  # Page indicators are a crucial part of any app that involves multiple pages. They help users to
  #understand the number of pages and their current position
  #  smooth_page_indicator: ^1.2.0+3
  share_plus: ^10.0.2
  url_launcher: ^6.3.0
  flutter_layout_grid: ^2.0.7
  # This plugin allows Flutter apps to discover network connectivity and
  # configure themselves accordingly. It can distinguish between cellular vs WiFi connection.
  connectivity_plus: ^6.1.3
  # For story
  story: ^1.1.0

  # This Flutter plugin provides an API for querying information about an application package.
  package_info_plus: ^8.0.2
  #  video_player: ^2.9.2
  flutter_rating_stars: ^1.1.0
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  #  scan: ^1.6.0
  #  mobile_scanner: ^6.0.7
  qr_code_scanner_plus: ^2.0.10+1
  animated_custom_dropdown: ^3.1.1
  provider: ^6.1.2
  flutter_date_range_picker: ^0.1.1
  delightful_toast: ^1.1.0
#  path_provider: ^2.1.5
#  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
#
#  fonts:
#    - family: Lato
#      fonts:
#        - asset: assets/fonts/Lato/Lato-Black.ttf
#          weight: 800
#        - asset: assets/fonts/Lato/Lato-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/Lato/Lato-Regular.ttf
#          weight: 500
#        - asset: assets/fonts/Lato/Lato-Light.ttf
#          weight: 300